import {
  FaTachometerAlt,
  FaBox,
  FaBuilding,
  FaUsers,
  FaFileInvoice,
  FaHeadset,
  FaCog,
} from "react-icons/fa";

export const tabs = [
  "Order Detail",
  "Order Requirements",
  "Contacts",
  "Documents",
  "Status History",
  "Account Manager",
];

// Sidebar menu items with corresponding icons and routes
export const menuItems = [
  { name: "Dashboard", icon: <FaTachometerAlt />, path: "/dashboard" },
  { name: "Order", icon: <FaBox />, path: "/order" },
  { name: "Company", icon: <FaBuilding />, path: "/company" },
  { name: "Users", icon: <FaUsers />, path: "/users" },
  { name: "Billings", icon: <FaFileInvoice />, path: "/billings" },
  { name: "Supports", icon: <FaHeadset />, path: "/supports" },
  { name: "Settings", icon: <FaCog />, path: "/settings" },
];

export const OrderList = [
  {
    id: 2279550,
    company: 'TL Flex Holdings LLC',
    status: 'Completed',
    placedBy: "Abc xyz",
    requester: "Jane Smith",
    externalId: "P123456",
    requesterEmail: "abc@xyz.com",
    orderDate: "2024-10-11",
    expectedDate: "2022-11-01",
    completionDate: "2022-11-10",
    serviceLevel: "Premium",
    Country: "Canada",
  },
  {
    id: 277541,
    company: 'TL Flex Holdings LLC',
    status: 'Pending',
    placedBy: "xyz wda",
    requester: "Jane Smith",
    externalId: "B9123455",
    requesterEmail: "abc@xyz.com",
    orderDate: "2024-10-11",
    expectedDate: "2015-11-01",
    completionDate: "2015-11-10",
    serviceLevel: "Premium",
    Country: "USA",
  },
  {
    id: 2679545,
    company: 'TL Flex Holdings LLC',
    status: 'Completed',
    placedBy: "adc zda",
    requester: "Jane Smith",
    externalId: "D5233256",
    requesterEmail: "abc@xyz.com",
    orderDate: "2024-10-11",
    expectedDate: "2025-11-01",
    completionDate: "2025-11-10",
    serviceLevel: "Premium",
    Country: "Germany",
  },
  {
    id: 2679544,
    company: 'TL Flex LLC',
    status: 'InProgress',
    placedBy: "lks cbd",
    requester: "Jane Smith",
    externalId: "W5123456",
    requesterEmail: "abc@xyz.com",
    orderDate: "2023-08-11",
    expectedDate: "2023-11-01",
    completionDate: "2024-11-10",
    serviceLevel: "Premium",
    Country: "USA",
  },
  {
    id: 2589549,
    company: 'SL Flex Holdings',
    status: 'Draft', placedBy: "John Doe",
    requester: "lkje vda",
    externalId: "X9823456",
    requesterEmail: "abc@xyz.com",
    orderDate: "2024-10-11",
    expectedDate: "2024-12-01",
    completionDate: "2024-11-10",
    serviceLevel: "Premium",
    Country: "India",
  }
];